=== GNOME/libgtop/dtd/libgtop-backend-info.dtd
<!ELEMENT BackendInfo (name,description?,comments?,authors,legalnotice)>
<!ELEMENT name (short_name,long_name?)>
<!ELEMENT short_name (#PCDATA)>
<!ELEMENT long_name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT authors (author)+>
<!ELEMENT author (author_name,author_email?)>
<!ELEMENT author_name (#PCDATA)>
<!ELEMENT author_email (#PCDATA)>

<!ELEMENT legalnotice (license,copyright?)>
<!ELEMENT license (#PCDATA)>

<!ELEMENT copyright (holder)+>
<!ELEMENT holder (holder_year?,holder_name,holder_email?)>
<!ELEMENT holder_year (#PCDATA)>
<!ELEMENT holder_name (#PCDATA)>
<!ELEMENT holder_email (#PCDATA)>

<!ELEMENT comments (comment)+>
<!ELEMENT comment (#PCDATA)>

=== GNOME/libgtop/sysdeps/linux/backend-info.xml
<?xml version="1.0"?> <!-- -*-xml-*- -->
<!DOCTYPE libgtop:backendinfo SYSTEM 'libgtop-backend-info.dtd'>
<libgtop:BackendInfo xmlns:libgtop="http://www.home-of-linux.org/libgtop/1.1">

  <name>
    <short_name>
      linux-sysdeps
    </short_name>

    <long_name>
      Linux sysdeps port.
    </long_name>
  </name>

  <description>
    This is the Linux sysdeps port which uses the /proc filesystem
    to get all the data.
  </description>

  <authors>
    <author>
      <author_name>
        Martin Baulig
      </author_name>
      <author_email>
        martin@home-of-linux.org
      </author_email>
    </author>
  </authors>

  <legalnotice>
    <license>
      GNU General Public License
    </license>
  </legalnotice>

</libgtop:BackendInfo>
